import type { ThemePack } from './word-search-types';

export const THEME_PACKS: ThemePack[] = [
  {
    id: 'animals',
    name: 'Animals',
    words: [
      'TIGER', 'LION', 'ELEPHANT', 'GIRAFFE', 'PENGUIN', 'DOLPHIN', 'EAGLE', 'PYTHON',
      'ZEBRA', 'MONKEY', 'RABBIT', 'FALCON', 'WHALE', 'PANDA', 'KOALA', 'OTTER',
      'JAGUAR', 'BISON', 'HAWK', 'PARROT', 'SHARK', 'COYOTE', 'RAVEN', 'GECKO',
      'MOOSE', 'SQUID', 'CRANE', 'VIPER', 'SLOTH', 'BADGER', 'LEMUR', 'TOUCAN',
      'COBRA', 'HERON', 'CAMEL', 'FERRET', 'IGUANA', 'MARTEN', 'OSPREY', 'SALMON',
      'TURKEY', 'WOMBAT', 'ALPACA', 'CRAB', 'DUCK', 'FINCH', 'GOOSE', 'HYENA',
      'IBIS', 'JACKAL', 'KITE', 'LLAMA', 'MINK', 'NEWT', 'OKAPI', 'PUMA',
      'QUAIL', 'ROBIN', 'STORK', 'TAPIR', 'URCHIN', 'VULTURE', 'WALRUS', 'YAK',
      'FROG', 'TROUT', 'EGRET', 'SEAL', 'DOVE', 'LYNX', 'BASS', 'CARP',
      'DEER', 'EEL', 'FOX', 'GULL', 'HORSE', 'KIWI', 'LARK', 'MOTH',
      'OWL', 'PIKE', 'RAM', 'SWAN', 'TOAD', 'WOLF', 'WREN', 'CROW',
      'BEAR', 'CHIMP', 'DINGO', 'ERMINE', 'GANNET', 'HUSKY', 'IMPALA', 'MACAW',
      'NARWHAL', 'ORIOLE', 'PELICAN', 'SKUNK',
    ],
  },
  {
    id: 'food',
    name: 'Food',
    words: [
      'PIZZA', 'SUSHI', 'BURGER', 'TACO', 'PASTA', 'WAFFLE', 'MANGO', 'STEAK',
      'SALMON', 'COOKIE', 'PRETZEL', 'RAMEN', 'CREPE', 'DONUT', 'BAGEL', 'CURRY',
      'FALAFEL', 'GYOZA', 'NACHOS', 'HUMMUS', 'PAELLA', 'KIMCHI', 'FONDUE', 'GELATO',
      'SCONE', 'CHURRO', 'TOFU', 'BISQUE', 'PESTO', 'QUICHE', 'BRIOCHE', 'GNOCCHI',
      'TEMPURA', 'SORBET', 'MUFFIN', 'RISOTTO', 'DUMPLING', 'PANINI', 'BROWNIE', 'SOUP',
      'BREAD', 'CHEESE', 'OLIVE', 'PECAN', 'GRAPE', 'MELON', 'LEMON', 'CAKE',
      'PIE', 'RICE', 'CORN', 'PLUM', 'PEAR', 'BACON', 'HAM', 'LAMB',
      'DUCK', 'BASIL', 'THYME', 'CUMIN', 'SAGE', 'GRAVY', 'CHILI', 'SALSA',
      'BROTH', 'CIDER', 'COCOA', 'HONEY', 'SYRUP', 'CANDY', 'FUDGE', 'TOAST',
      'CRACKER', 'NOODLE', 'KEBAB', 'GYRO', 'OKRA', 'PEACH', 'BERRY', 'KIWI',
      'PAPAYA', 'GUAVA', 'FIG', 'DATE', 'NUT', 'SEED', 'ROLL', 'TORTE',
      'COBBLER', 'TRUFFLE', 'GUMBO', 'FRITTER', 'CEVICHE', 'TAMALE', 'SAMOSA', 'BIRYANI',
      'CRUMPET', 'BISCUIT', 'GRANOLA', 'TAHINI',
    ],
  },
  {
    id: 'countries',
    name: 'Countries',
    words: [
      'BRAZIL', 'JAPAN', 'FRANCE', 'EGYPT', 'CANADA', 'MEXICO', 'INDIA', 'SPAIN',
      'ITALY', 'PERU', 'NORWAY', 'CHILE', 'CUBA', 'GHANA', 'NEPAL', 'KENYA',
      'SWEDEN', 'TURKEY', 'PANAMA', 'FINLAND', 'MOROCCO', 'POLAND', 'GREECE', 'BELIZE',
      'LATVIA', 'FIJI', 'OMAN', 'QATAR', 'TONGA', 'MALTA', 'CHINA', 'RUSSIA',
      'SUDAN', 'CHAD', 'MALI', 'NIGER', 'TOGO', 'BENIN', 'GABON', 'NAURU',
      'SAMOA', 'GUYANA', 'HAITI', 'LAOS', 'IRAN', 'IRAQ', 'YEMEN', 'SYRIA',
      'JORDAN', 'LIBYA', 'TUNISIA', 'ANGOLA', 'ZAMBIA', 'MALAWI', 'UGANDA', 'RWANDA',
      'BURUNDI', 'ERITREA', 'BHUTAN', 'BRUNEI', 'CYPRUS', 'MONACO', 'SERBIA', 'CROATIA',
      'BOSNIA', 'ALBANIA', 'ARMENIA', 'GEORGIA', 'ESTONIA', 'UKRAINE', 'BELARUS', 'MOLDOVA',
      'AUSTRIA', 'BELGIUM', 'DENMARK', 'ICELAND', 'IRELAND', 'PORTUGAL', 'ROMANIA', 'HUNGARY',
      'SLOVAKIA', 'URUGUAY', 'BOLIVIA', 'ECUADOR', 'SURINAME', 'VIETNAM', 'MYANMAR', 'TAIWAN',
      'MONGOLIA', 'BAHRAIN', 'KUWAIT', 'LEBANON', 'SENEGAL', 'LIBERIA', 'SIERRA', 'ANDORRA',
      'VANUATU', 'PALAU', 'COMOROS', 'LESOTHO',
    ],
  },
  {
    id: 'sports',
    name: 'Sports',
    words: [
      'TENNIS', 'SOCCER', 'HOCKEY', 'RUGBY', 'BOXING', 'SKIING', 'DIVING', 'SURFING',
      'ROWING', 'FENCING', 'GOLF', 'KARATE', 'POLO', 'SQUASH', 'ARCHERY', 'JUDO',
      'CRICKET', 'CURLING', 'LACROSSE', 'CYCLING', 'SKATING', 'BOWLING', 'SPRINT',
      'JAVELIN', 'DISCUS', 'LUGE', 'DARTS', 'BIATHLON', 'RALLY', 'PADDLE',
      'BASEBALL', 'SOFTBALL', 'HANDBALL', 'SAILING', 'KAYAK', 'CANOE', 'BADMINTON',
      'CLIMBING', 'HURDLES', 'RELAY', 'HAMMER', 'SHOTPUT', 'VAULT', 'RINGS',
      'BEAM', 'FLOOR', 'BARS', 'TRIATHLON', 'MARATHON', 'DECATHLON', 'BOBSLED',
      'SKELETON', 'SLALOM', 'MOGULS', 'HALFPIPE', 'SNOOKER', 'BILLIARDS', 'CHESS',
      'YOGA', 'PILATES', 'CAPOEIRA', 'AIKIDO', 'KENDO', 'SUMO', 'WUSHU',
      'TAEKWONDO', 'FUTSAL', 'NETBALL', 'PELOTA', 'RAFTING', 'RAPPEL', 'HIKING',
      'RUNNING', 'JOGGING', 'WALKING', 'SWIM', 'THROW', 'CATCH', 'KICK',
      'VOLLEY', 'SERVE', 'SMASH', 'BLOCK', 'TACKLE', 'PASS', 'SHOOT',
      'SCORE', 'GOAL', 'PITCH', 'FIELD', 'COURT', 'RINK', 'TRACK', 'ARENA',
      'GYM', 'POOL', 'RING', 'MAT', 'CROQUET', 'PARKOUR',
    ],
  },
  {
    id: 'colors',
    name: 'Colors',
    words: [
      'CRIMSON', 'VIOLET', 'INDIGO', 'SCARLET', 'BRONZE', 'SILVER', 'GOLDEN', 'CORAL',
      'IVORY', 'MAROON', 'TEAL', 'AMBER', 'JADE', 'RUBY', 'COBALT', 'ONYX',
      'PEACH', 'PLUM', 'KHAKI', 'MAUVE', 'OLIVE', 'SLATE', 'EBONY', 'AZURE',
      'CREAM', 'COPPER', 'PEARL', 'LILAC', 'SAGE', 'TAUPE', 'SALMON', 'SIENNA',
      'OCHRE', 'RUSSET', 'UMBER', 'SEPIA', 'DENIM', 'LEMON', 'LIME', 'MINT',
      'MOSS', 'PINE', 'FERN', 'FOREST', 'HUNTER', 'KELLY', 'EMERALD', 'CELERY',
      'AQUA', 'CYAN', 'TURQUOISE', 'SAPPHIRE', 'NAVY', 'ROYAL', 'SKY', 'STEEL',
      'POWDER', 'ARCTIC', 'MAGENTA', 'FUCHSIA', 'ROSE', 'BLUSH', 'DUSTY', 'WINE',
      'GARNET', 'CHERRY', 'BRICK', 'RUST', 'FLAME', 'TANGERINE', 'APRICOT', 'SAND',
      'WHEAT', 'BUFF', 'BEIGE', 'BONE', 'SNOW', 'CLOUD', 'SMOKE', 'ASH',
      'CHARCOAL', 'IRON', 'PEWTER', 'TIN', 'LEAD', 'GRAPHITE', 'JET', 'RAVEN',
      'INK', 'OBSIDIAN', 'MIDNIGHT', 'DUSK', 'SUNSET', 'DAWN', 'SAFFRON', 'GOLD',
      'HONEY', 'BUTTER', 'CANARY', 'FLAX',
    ],
  },
  {
    id: 'movies',
    name: 'Movies',
    words: [
      'JAWS', 'FROZEN', 'ALIEN', 'ROCKY', 'SHREK', 'BAMBI', 'MULAN', 'BRAVE',
      'COCO', 'DUNE', 'JOKER', 'TENET', 'MOANA', 'PSYCHO', 'GREASE', 'CARS',
      'BOLT', 'LOGAN', 'GHOST', 'SCREAM', 'FARGO', 'SPLIT', 'CREED', 'SPARK',
      'ROGUE', 'BLADE', 'NEMO', 'ARGO', 'WICKED', 'ZODIAC', 'AVATAR', 'SPEED',
      'HEAT', 'CRASH', 'DRIVE', 'FURY', 'TROY', 'TRON', 'VICE', 'SIGNS',
      'PRIME', 'TAKEN', 'RUSH', 'HUGO', 'LIFE', 'FOCUS', 'CLICK', 'IRON',
      'GLORY', 'SNATCH', 'SCOOP', 'SULLY', 'ARRIVAL', 'DUNKIRK', 'GRAVITY', 'HER',
      'UP', 'LEON', 'HOOK', 'TWISTER', 'TITANIC', 'AMADEUS', 'PLATOON', 'MEMENTO',
      'GLADIATOR', 'SEVEN', 'MATRIX', 'ALADDIN', 'ENCANTO', 'INSIDE', 'SOUL', 'LUCA',
      'ONWARD', 'TURBO', 'RIO', 'SING', 'STORKS', 'TROLLS', 'TANGLED', 'CLUELESS',
      'SELMA', 'TOPAZ', 'RAMBO', 'COBRA', 'SPAWN', 'DREDD', 'WANTED', 'NERVE',
      'SNIPER', 'SICARIO', 'PATROL', 'CASINO', 'CLOSER', 'JUMPER', 'CORALINE', 'TREMORS',
      'CONTACT', 'VOLCANO', 'INFERNO', 'EVEREST',
    ],
  },
];
